const PDFDocument = require('pdfkit')

const generatePatientReport = (res, record) => {
  const doc = new PDFDocument({ margin: 50 })

  res.setHeader('Content-Type', 'application/pdf')
  res.setHeader(
    'Content-Disposition',
    `attachment; filename=patient-report-${record.id}.pdf`
  )

  doc.pipe(res)

  // Title
  doc.fontSize(22).font('Helvetica-Bold').text('MediSync Healthcare', { align: 'center' })
  doc.fontSize(16).font('Helvetica').text('Patient Consultation Report', { align: 'center' })
  doc.moveDown()
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
  doc.moveDown()

  // Patient Info
  doc.fontSize(13).font('Helvetica-Bold').text('Patient Information')
  doc.fontSize(11).font('Helvetica')
  doc.text(`Name: ${record.patient_name || 'N/A'}`)
  doc.text(`Email: ${record.patient_email || 'N/A'}`)
  doc.text(`Age: ${record.patient_age || 'N/A'} | Gender: ${record.patient_gender || 'N/A'}`)
  doc.text(`Symptoms: ${record.symptoms || 'None reported'}`)
  doc.moveDown()

  // Appointment Info
  doc.fontSize(13).font('Helvetica-Bold').text('Appointment Details')
  doc.fontSize(11).font('Helvetica')
  doc.text(`Doctor: ${record.doctor_name || 'N/A'}`)
  doc.text(`Date: ${record.slot_date || 'N/A'} at ${record.start_time || 'N/A'}`)
  doc.text(`Appointment ID: ${record.appointment_id || 'N/A'}`)
  doc.moveDown()

  // Medical Info
  doc.fontSize(13).font('Helvetica-Bold').text('Medical Details')
  doc.fontSize(11).font('Helvetica')
  doc.text(`Diagnosis: ${record.diagnosis || 'Pending'}`)
  doc.text(`Prescription: ${record.prescription || 'None'}`)
  doc.text(`Consultation Notes: ${record.consultation_notes || 'None'}`)
  doc.moveDown()

  // Footer
  doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke()
  doc.moveDown(0.5)
  doc.fontSize(10).fillColor('#888').text('Generated by MediSync Healthcare System', { align: 'center' })

  doc.end()
}

module.exports = { generatePatientReport }