const PDFDocument = require('pdfkit')

// ==========================
// GENERATE PATIENT PDF
// ==========================
const generatePatientReport = (
  res,
  patientRecord
) => {

  const doc = new PDFDocument()

  // ==========================
  // RESPONSE HEADERS
  // ==========================
  res.setHeader(
    'Content-Type',
    'application/pdf'
  )

  res.setHeader(
    'Content-Disposition',
    `attachment; filename=patient-report-${patientRecord.id}.pdf`
  )

  // ==========================
  // PIPE PDF
  // ==========================
  doc.pipe(res)

  // ==========================
  // TITLE
  // ==========================
  doc
    .fontSize(24)
    .text(
      'Healthcare Consultation Report',
      {
        align: 'center'
      }
    )

  doc.moveDown()

  // ==========================
  // PATIENT DETAILS
  // ==========================
  doc
    .fontSize(16)
    .text(
      `Appointment ID: ${patientRecord.appointment_id}`
    )

  doc.moveDown()

  doc.text(
    `Diagnosis: ${patientRecord.diagnosis}`
  )

  doc.moveDown()

  doc.text(
    `Prescription: ${patientRecord.prescription}`
  )

  doc.moveDown()

  doc.text(
    `Consultation Notes: ${patientRecord.consultation_notes}`
  )

  doc.moveDown()

  doc.text(
    `Created At: ${patientRecord.created_at}`
  )

  // ==========================
  // FOOTER
  // ==========================
  doc.moveDown()

  doc
    .fontSize(12)
    .text(
      'Generated by MediSync Healthcare System',
      {
        align: 'center'
      }
    )

  // ==========================
  // FINALIZE
  // ==========================
  doc.end()
}

module.exports = {
  generatePatientReport
}